name: roboweather
channels:
  - conda-forge
dependencies:
  - python=3.11
  - joblib
  - h5py
  - numpy
  - pandas
  - pygrib
  - pyproj
  - pytest
  - requests
  - scikit-learn=1.5.2
  - textual
  - pip
  - pip:
      - -e .
